[[repos]]
repo = "https://github.com/google/yamlfmt"
rev = "v0.13.0"

[[repos.hooks]]
id = "yamlfmt"
args = []

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.6.9"

[[repos.hooks]]
id = "ruff"
args = ["--fix"]

[[repos.hooks]]
id = "ruff-format"

[[repos]]
repo = "https://github.com/pre-commit/mirrors-mypy"
rev = "v1.11.2"

[[repos.hooks]]
id = "mypy"
additional_dependencies = ["pydantic"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "pytest-check"
name = "pytest-check"
stages = ["pre-commit"]
types = ["python"]
entry = "pytest"
language = "system"
pass_filenames = false

[[repos]]
repo = "https://github.com/executablebooks/mdformat"
rev = "0.7.17"

[[repos.hooks]]
id = "mdformat"
additional_dependencies = ["mdformat-gfm"]
